### ISSUE TITLE
Consider adding musical-artifacts to the links or resources section

### ISSUE THREAD

**Issue by lfzawacki** [ad-si/awesome-soundfonts#1]
This website hosts and categorizes several soundfonts and has a (limited) preview of the soundfont contents: https://musical-artifacts.com/artifacts?tags=soundfont  

DISCLAIMER: I'm the creator of the project but everything is open source and focused on freely licensed files.

Thanks

**Comment by ad-si** [comment]
Thanks, that's a cool website! Keep up the great work!

Added it in 299a4e9.
