### ISSUE TITLE
Few resources to add

### ISSUE THREAD

**Issue by spessasus** [ad-si/awesome-soundfonts#2]
Hi, here are some soundfont resources and players I've found:
### Information
- [Soundfont specification](https://freepats.zenvoid.org/sf2/sfspec24.pdf) - the core document of the soundfont standard.
- [Unofficial SF3 specification](https://github.com/FluidSynth/fluidsynth/wiki/SoundFont3Format) - explains how sf3 files work.
### Players
- [MidiPlayer6](https://falcosoft.hu/softwares.html) - probably the best soundfont player I've found. It supports sf3, sf2, a LOT of system exclusive messages, MIDI tuning standard, multi-port MIDIs and more. (And it has a great performance)
- [fluidsynth](https://github.com/FluidSynth/fluidsynth) - Fully compliant with the SoundFont standard, written in pure C. (and the first software soundfont synth made I think)
- [SpessaSynth](https://spessasus.github.io/SpessaSynth/) - created by me, a complete sf2 and sf2 synthesizer and MIDI player that runs in the browser. Similar feature set to the MidiPlayer6.

**Comment by ad-si** [comment]
Thanks, great additions! Added them in ba61f82.

SpessaSynth is a really cool project! Keep it up!
